# This is a basic workflow to help you get started with Actions

name: make executable binary

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Make binary
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # dev env
    strategy:
      matrix:
        python-version: [3.8]
    # variables
    env:
      DIST_FOLDER: dist/linux
      BUILD_FOLDER: build
      EXE_NAME: sshd_guard-linux
      ENTRY_NAME: main
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout branch
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install pyinstaller
        run: pip3 install pyinstaller

      # Runs a set of commands using the runners shell
      - name: Pack binary
        run: |
          pyinstaller -F --clean --distpath $DIST_FOLDER --workpath $BUILD_FOLDER --specpath $BUILD_FOLDER --name $EXE_NAME ./src/$ENTRY_NAME.py
          zip -r $EXE_NAME.zip $DIST_FOLDER/*

      # Publish Release
      - name: Publish Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "${{ env.EXE_NAME }}.zip"
          tags: false
          draft: false