# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: make binary
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # env
    strategy:
      matrix:
        python-version: [3.8]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout branch
        uses: actions/checkout@master

      # Runs a single command using the runners shell
      - name: install pyinstaller
        run: python -m pip3 pyinstaller

      # Runs a set of commands using the runners shell
      - name: pack binary for linux
        env:
          DIST_FOLDER: dist/linux
          BUILD_FOLDER: build
          EXE_NAME: sshd_guard
          ENTRY_NAME: main
        run: pyinstaller -F --clean --distpath $DIST_FOLDER --workpath $BUILD_FOLDER --specpath $BUILD_FOLDER --name $EXE_NAME ./src/$ENTRY_NAME.py
